//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favourite
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int Release { get; set; }
        public string Genre { get; set; }
        public string Image { get; set; }
    }
}
